'use strict';

const ROOM_CONFIG = {
    MAX_PLAYERS_PER_ROOM: 20,
    MIN_PLAYERS_START_GAME: 3,
    TIME_STARTING_COUNTDOWN: 5,
    TIME_PLAYING_COUNTDOWN: 60,
    TIME_VOTING_COUNTDOWN: 10,
    TIME_PRESENTANTE_COUNTDOWN: 10,
    NUMBER_OF_ROUNDS: 20
};

module.exports = ROOM_CONFIG;