'use strict';

const ROOM_CONFIG = {
    MAX_PLAYERS_PER_ROOM: 10,
    MIN_PLAYERS_START_GAME: 3,
    TIME_STARTING_COUNTDOWN: 10,
    TIME_PLAYING_COUNTDOWN: 30,
    TIME_VOTING_COUNTDOWN: 15,
    NUMBER_OF_ROUNDS: 10
};

module.exports = ROOM_CONFIG;