'use strict';

const ROOM_CONFIG = {
    MAX_PLAYERS_PER_ROOM: 10,
    MIN_PLAYERS_START_GAME: 2,
    TIME_PER_ROUND: 60,
    TIME_STARTING_COUNTDOWN: 10,
    TIME_PLAYING_COUNTDOWN: 10,
    TIME_VOTING_COUNTDOWN: 10
}

module.exports = ROOM_CONFIG;